"use strict";
var clientes = /** @class */ (function () {
    function clientes(nombre, rut, edad, genero, fecha_nac, email, region, comuna) {
        this.nombre = nombre;
        this.rut = rut;
        this.edad = edad;
        this.genero = genero;
        this.fecha_nac = fecha_nac;
        this.email = email;
        this.region = region;
        this.comuna = comuna;
    }
    return clientes;
}());
(function () {
    var doc = document.getElementById('cuerpo');
    var cliente1 = new clientes('Felipe Gonzales', '20.092.871-0', '21', 'Masculino', '21 de diciembre 1999', 'felipgonz@mail.com', 'Valparaiso', 'Valparaiso');
    var cliente2 = new clientes('Franco Gomez', '20.007.891-k', '25', 'Masculino', '2 de enero 1996', 'destructordecubos91@mail.com', 'Valparaiso', 'Valparaiso');
    cartaCliente(doc, cliente1);
    Editar(doc, cliente1);
    ListAntecedentes(doc, cliente1);
})();
function cartaCliente(doc, cliente) {
    var div1 = document.createElement('div');
    var div2 = document.createElement('div');
    var divimg = document.createElement('div');
    var img = document.createElement('img');
    var divCli = document.createElement('div');
    var cuerpCli = document.createElement('div');
    var nombreCli = document.createElement('h5');
    var infoCli = document.createElement('p');
    var carta;
    var fila;
    var imgCli;
    var imgPerfil;
    var Cli;
    var cueCli;
    var nomCli;
    var infCli;
    carta.appendChild(div1);
    carta.class = "card mb-3";
    fila.appendChild(div2);
    fila.class = "row g-0";
    imgCli.appendChild(divimg);
    imgCli.class = "col-md-4";
    imgPerfil.appendChild(img);
    imgPerfil.innerHTML = ' src="..." class="img-fluid rounded-start" alt="..." ';
    Cli.appendChild(divCli).class = "col-md-8";
    cueCli.appendChild(cuerpCli).class = "card-body";
    nomCli.appendChild(nombreCli).innerHTML = cliente.nombre;
    infCli.appendChild(infoCli).innerHTML = cliente.fecha_nac + ", " + cliente.edad + " Años";
    doc.appendChild(carta);
}
function ListAntecedentes(doc, cliente) {
}
function Editar(doc, cliente) {
    var editar = document.createElement('li');
    editar.addEventListener("click", Formulario(doc, cliente));
}
function Formulario(doc, cliente) {
    var forms = document.createElement('form');
    doc.appendChild(forms);
    doc.class = "row g-3 needs-validation";
    var campos = document.createElement('ul');
    forms.appendChild(campos);
    //primer campo: nombre completo
    var nomli;
    var nomdiv;
    var nomlab;
    var nombre;
    var linom = document.createElement('li');
    var divnom = document.createElement('div');
    var labnom = document.createElement('label');
    var inpnom = document.createElement('input');
    nomli.appendChild(linom);
    nomdiv.appendChild(divnom);
    nomlab.appendChild(labnom);
    nombre.appendChild(inpnom);
    nomdiv.class = "col";
    nomlab.for = "nombreCliente";
    nomlab.class = "form-label";
    nomlab.innerHTML = "Nombre Completo";
    nombre.type = "text";
    nombre.class = "form-control";
    nombre.id = "nombreCliente";
    nombre.value = cliente.nombre;
    //segundo campo: rut cliente
    var rutli;
    var rutdiv;
    var rutlab;
    var rut;
    var lirut = document.createElement('li');
    var divrut = document.createElement('div');
    var labrut = document.createElement('label');
    var inprut = document.createElement('input');
    rutli.appendChild(lirut);
    rutdiv.appendChild(divrut);
    rutlab.appendChild(labrut);
    rut.appendChild(inprut);
    rutdiv.class = "col";
    rutlab.for = "rutCliente";
    rutlab.class = "form-label";
    rutlab.innerHTML = "Rut";
    rut.type = "text";
    rut.class = "form-control";
    rut.id = "rutCliente";
    rut.pattern = "^[0-9]{8}-[0-9Kk]{1}$";
    rut.value = cliente.rut;
    //tercer campo: edad cliente
    var edadli;
    var edaddiv;
    var edadlab;
    var edad;
    var liedad = document.createElement('li');
    var divedad = document.createElement('div');
    var labedad = document.createElement('label');
    var inpedad = document.createElement('input');
    edadli.appendChild(liedad);
    edaddiv.appendChild(divedad);
    edadlab.appendChild(labedad);
    edad.appendChild(inpedad);
    edaddiv.class = "col";
    edadlab.for = "edadCliente";
    edadlab.class = "form-label";
    edadlab.innerHTML = "edad";
    edad.type = "number";
    edad.class = "form-control";
    edad.id = "edadCliente";
    edad.value = cliente.edad;
    //cuarto campo: genero cliente
    var genli;
    var gendiv;
    var genlab;
    var genero;
    var ligen = document.createElement('li');
    var divgen = document.createElement('div');
    var labgen = document.createElement('label');
    var inpgen = document.createElement('input');
    genli.appendChild(ligen);
    gendiv.appendChild(divgen);
    genlab.appendChild(labgen);
    genero.appendChild(inpgen);
    gendiv.class = "col";
    genlab.for = "generoCliente";
    genlab.class = "form-label";
    genlab.innerHTML = "Genero";
    genero.type = "text";
    genero.class = "form-control";
    genero.id = "generoCliente";
    genero.value = cliente.genero;
    //quinto campo: fecha de nacimiento
    var nacli;
    var nacdiv;
    var naclab;
    var nacimiento;
    var linac = document.createElement('li');
    var divnac = document.createElement('div');
    var labnac = document.createElement('label');
    var inpnac = document.createElement('input');
    nacli.appendChild(linac);
    nacdiv.appendChild(divnac);
    naclab.appendChild(labnac);
    nacimiento.appendChild(inpnac);
    nacdiv.class = "col";
    naclab.for = "nacCliente";
    naclab.class = "form-label";
    naclab.innerHTML = "Fecha nacimiento";
    nacimiento.type = "text";
    nacimiento.class = "form-control";
    nacimiento.id = "nacCliente";
    nacimiento.value = cliente.fecha_nac;
    //sexto campo: correo electronico
    var mailli;
    var maildiv;
    var maillab;
    var email;
    var limail = document.createElement('li');
    var divmail = document.createElement('div');
    var labmail = document.createElement('label');
    var inpmail = document.createElement('input');
    mailli.appendChild(limail);
    maildiv.appendChild(divmail);
    maillab.appendChild(labmail);
    email.appendChild(inpmail);
    maildiv.class = "col";
    maillab.for = "mailCliente";
    maillab.class = "form-label";
    maillab.innerHTML = "Email";
    email.type = "email";
    email.class = "form-control";
    email.id = "mailCliente";
    email.value = cliente.rut;
    //septimo campo: region
    var regli;
    var regdiv;
    var reglab;
    var region;
    var lireg = document.createElement('li');
    var divreg = document.createElement('div');
    var labreg = document.createElement('label');
    var inpreg = document.createElement('input');
    regli.appendChild(lireg);
    regdiv.appendChild(divreg);
    reglab.appendChild(labreg);
    region.appendChild(inpreg);
    regdiv.class = "col";
    reglab.for = "regionCliente";
    reglab.class = "form-label";
    reglab.innerHTML = "Region";
    region.type = "text";
    region.class = "form-control";
    region.id = "regionCliente";
    region.value = cliente.region;
    //octavo campo: comuna
    var comli;
    var comdiv;
    var comlab;
    var comuna;
    var licom = document.createElement('li');
    var divcom = document.createElement('div');
    var labcom = document.createElement('label');
    var inpcom = document.createElement('input');
    comli.appendChild(licom);
    comdiv.appendChild(divcom);
    comlab.appendChild(labcom);
    comuna.appendChild(inpcom);
    comdiv.class = "col";
    comlab.for = "comCliente";
    comlab.class = "form-label";
    comlab.innerHTML = "Comuna";
    comuna.type = "text";
    comuna.class = "form-control";
    comuna.id = "comCliente";
    comuna.value = cliente.comuna;
}
